apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduling-service
  labels:
    app: scheduling-service
    app.kubernetes.io/name: scheduling-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: whispr
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: scheduling-service
