apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  labels:
    app: scheduling-service
    app.kubernetes.io/name: scheduling-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: whispr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 3001
      targetPort: grpc
      protocol: TCP
  selector:
    app: scheduling-service
